name: CI - .NET Build & Tests
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: false
      - name: Restore
        run: dotnet restore DemoUnitTest_ConsoleApp.sln
      - name: Build
        run: dotnet build DemoUnitTest_ConsoleApp.sln --configuration Release --no-restore
      - name: Test + coverage
        run: >
          dotnet test UnitTest/UnitTest.csproj
          --configuration Release --no-build
          --collect:"XPlat Code Coverage"
          --logger "trx;LogFileName=test-results.trx"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/**/coverage.cobertura.xml
